import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import NavigationBar from "@/components/footer";
import NextTopLoader from "nextjs-toploader";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   generator: "Next.js",
//   manifest: "/manifest.json"
// };

const APP_NAME = "Mreneo Management App";
const APP_DEFAULT_TITLE = "Mreneo Management";
const APP_TITLE_TEMPLATE = "%s - Mreneo Management";
const APP_DESCRIPTION = "Generated by create next app";

export const metadata: Metadata = {
  applicationName: APP_NAME,
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_DEFAULT_TITLE,
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: APP_NAME,
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
  twitter: {
    card: "summary",
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " h-full"}>
        <div className="flex flex-col h-full">
          <NextTopLoader
            color="#2299DD"
          />
          <Header />
          <CookiesProvider>
            <div className="min-h-0 h-full overflow-auto">
              {children}
            </div>
          </CookiesProvider>
          <NavigationBar />
        </div>
      </body>
    </html>
  );
}
